# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Fokuus/aaa
  branch: main
  identity_url: https://auth.decapbridge.com/sites/7355274a-69ed-4e89-ad0d-fd3fdf2e835d
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://intermediate-astro-kit-decap-cms.netlify.app

# Default media folder settings
media_folder: src/assets/images # Main media folder
public_folder: src/assets/images # Main public folder

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    label: "Blog" # Used in the admin dashboard UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Is it a featured post?", name: "isFeatured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Project Image", name: "image", widget: "image" }
      - { label: "Featured Project", name: "featured", widget: "boolean", default: false }
      - { label: "Layout", name: "layout", widget: "select", options: ["regular", "tall", "wide"], default: "regular" }
      - { label: "Display Order", name: "order", widget: "number", default: 0, value_type: "int" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Project Description", name: "body", widget: "markdown" }
